apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx

