apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
          
