apiVersion: v1
kind: Pod
metadata:
  name: pract-pod
spec:
  containers:
    - name: nginx-c
      image: nginx
      volumeMounts:
        - name: simple-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: simple-storage
      persistentVolumeClaim:
        claimName: simple-pvc
