apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
    env: dev
spec:  #spec will contain what to run
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

